site_name: Labrakates
site_author: Ben Browning

repo_url: https://github.com/labrakates/pipelines

theme:
  name: material
  features:
    - navigation.expand
    - navigation.sections

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Overview: index.md
  - Installation:
    - Prerequisites: prerequisites.md
    - Creating the pipelines: creating_pipelines.md
  - Data Generation:
    - Your first data generation: first_data_generation.md
  - Training:
    - Your first model training: first_training.md
