site_name: Labrakates
site_author: Ben Browning

repo_url: https://github.com/labrakates/pipelines

theme:
  name: material
  features:
    - navigation.sections

nav:
  - Overview: index.md
  - Installation:
    - Prerequisites: prerequisites.md
    - Creating the pipelines: creating_pipelines.md
    - Your first data generation: first_data_generation.md
